
spring:
  application.name: example-integrationtest

--- ################################################################################################

spring.profiles: integrationtest

--- ################################################################################################
